export enum ApiEndpoints {
    REGISTRATION = 'auth/registration',
    LOGIN = 'auth/login',
    CHECK_EMAIL = 'auth/check-email',
    CONFIRM_EMAIL = 'auth/confirm-email',
    CHANGE_PASSWORD = 'auth/change-password',
    REVIEW = 'feedback',
    LOGIN_GOOGLE = '/auth/google',
    TRAINING = 'training',
    TRAINING_LIST = 'catalogs/training-list',
    CURRENT_USER = 'user/me',
    USER = 'user',
    IMAGE = 'upload-image',
    TARIFS = 'catalogs/tariff-list',
    NEW_TARIF = 'tariff',
    USER_JOINT_TRAINING_LIST = 'catalogs/user-joint-training-list',
    TRAINING_PALS_LIST = 'catalogs/training-pals',
    INVITE = 'invite',
}
